# Generated by Django 2.1.2 on 2019-09-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_title', models.CharField(max_length=50)),
                ('flat_title', models.CharField(max_length=50)),
                ('bedroom', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('tenacy_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HouseRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_for', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('moved_in', models.DateTimeField(auto_now_add=True)),
                ('caution_fee', models.IntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('marital_status', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('State_of_origin', models.CharField(max_length=50)),
                ('Religion', models.CharField(max_length=50)),
                ('Spouse_name', models.CharField(max_length=50)),
                ('telphone_no', models.CharField(max_length=50)),
                ('office_addr', models.CharField(max_length=500)),
                ('previous_home_addr', models.CharField(max_length=500)),
                ('sponsor_addr', models.CharField(max_length=500)),
                ('sponsor_phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_for', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('waste_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='houserent',
            name='rent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Tenant'),
        ),
        migrations.AddField(
            model_name='complain',
            name='complain_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Tenant'),
        ),
    ]
